#!/usr/bin/bash
#
# Adopt existing baremetal nodes for TNF deployment.
#
# Parses inventory_baremetal.ini, validates BMC credentials via Redfish,
# and generates ironic_nodes.json + config_baremetal_fencing.sh for dev-scripts.
#
# Usage:
#   adopt-baremetal.sh [options]
#
# Options:
#   --cluster-name NAME   Cluster name for output directory (default: ostest)
#   --skip-verify         Skip BMC credential verification
#   --verify-only         Only verify BMC credentials, don't generate artifacts
#   --config-base FILE    Base config to derive baremetal config from
#   -h, --help            Show this help message

set -o nounset
set -o errexit
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OC_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

CLUSTER_NAME="${CLUSTER_NAME:-ostest}"
SKIP_VERIFY=false
VERIFY_ONLY=false
CONFIG_BASE=""
INVENTORY="${OC_DIR}/inventory_baremetal.ini"

# Node data arrays — populated by parse_inventory
declare -a NODE_NAMES=()
declare -a NODE_BMC_IPS=()
declare -a NODE_BMC_USERS=()
declare -a NODE_BMC_PASSES=()
declare -a NODE_BOOT_MACS=()

# Group defaults
BMC_VERIFY_CA="False"
CPU_ARCH="x86_64"

##############################################################################
# Helpers
##############################################################################

die() { echo "Error: $*" >&2; exit 1; }

info() { echo "==> $*"; }

##############################################################################
# Argument parsing
##############################################################################

parse_args() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --cluster-name)
                CLUSTER_NAME="$2"
                shift 2
                ;;
            --skip-verify)
                SKIP_VERIFY=true
                shift
                ;;
            --verify-only)
                VERIFY_ONLY=true
                shift
                ;;
            --config-base)
                CONFIG_BASE="$2"
                shift 2
                ;;
            -h|--help)
                head -17 "$0" | tail -12
                exit 0
                ;;
            *)
                die "Unknown option: $1. Run '$0 --help' for usage."
                ;;
        esac
    done
}

##############################################################################
# Wizard — interactive inventory creation
##############################################################################

run_wizard() {
    info "No inventory_baremetal.ini found — starting interactive wizard"
    echo ""

    local node_count
    read -rp "Number of baremetal nodes [2]: " node_count
    node_count="${node_count:-2}"

    if [[ "${node_count}" -lt 2 ]]; then
        die "TNF requires at least 2 nodes"
    fi

    local tmp_inventory
    tmp_inventory=$(mktemp)
    {
        echo "# Generated by adopt-baremetal.sh wizard"
        echo ""
        echo "[baremetal_nodes]"
    } > "${tmp_inventory}"

    for ((i = 0; i < node_count; i++)); do
        local default_name="master-${i}"
        echo ""
        echo "--- Node $((i + 1)) of ${node_count} ---"

        local name bmc_ip bmc_user bmc_pass boot_mac
        read -rp "  Hostname [${default_name}]: " name
        name="${name:-${default_name}}"

        read -rp "  BMC IP address: " bmc_ip
        [[ -z "${bmc_ip}" ]] && die "BMC IP is required"

        read -rp "  BMC username [admin]: " bmc_user
        bmc_user="${bmc_user:-admin}"

        read -rsp "  BMC password: " bmc_pass
        echo ""
        [[ -z "${bmc_pass}" ]] && die "BMC password is required"

        read -rp "  Boot MAC address: " boot_mac
        [[ -z "${boot_mac}" ]] && die "Boot MAC is required"

        echo "${name} bmc_ip=${bmc_ip} bmc_user=${bmc_user} bmc_pass=${bmc_pass} boot_mac=${boot_mac}" >> "${tmp_inventory}"
    done

    {
        echo ""
        echo "[baremetal_nodes:vars]"
        echo "bmc_driver=redfish"
        echo "bmc_verify_ca=False"
        echo "cpu_arch=x86_64"
    } >> "${tmp_inventory}"

    mv "${tmp_inventory}" "${INVENTORY}"
    echo ""
    info "Inventory written to inventory_baremetal.ini"
}

##############################################################################
# INI parser
##############################################################################

parse_inventory() {
    [[ -f "${INVENTORY}" ]] || die "Inventory file not found: ${INVENTORY}"

    local in_nodes=false
    local in_vars=false

    while IFS= read -r line || [[ -n "${line}" ]]; do
        # Strip comments and leading/trailing whitespace
        line="${line%%#*}"
        line="${line#"${line%%[![:space:]]*}"}"
        line="${line%"${line##*[![:space:]]}"}"
        [[ -z "${line}" ]] && continue

        if [[ "${line}" == "[baremetal_nodes]" ]]; then
            in_nodes=true
            in_vars=false
            continue
        elif [[ "${line}" == "[baremetal_nodes:vars]" ]]; then
            in_nodes=false
            in_vars=true
            continue
        elif [[ "${line}" =~ ^\[.*\] ]]; then
            in_nodes=false
            in_vars=false
            continue
        fi

        if ${in_vars}; then
            local key val
            key="${line%%=*}"
            val="${line#*=}"
            case "${key}" in
                bmc_verify_ca) BMC_VERIFY_CA="${val}" ;;
                cpu_arch)      CPU_ARCH="${val}" ;;
            esac
            continue
        fi

        if ${in_nodes}; then
            local name rest
            name="${line%% *}"
            rest="${line#* }"

            local bmc_ip="" bmc_user="" bmc_pass="" boot_mac=""
            for pair in ${rest}; do
                local key val
                key="${pair%%=*}"
                val="${pair#*=}"
                case "${key}" in
                    bmc_ip)   bmc_ip="${val}" ;;
                    bmc_user) bmc_user="${val}" ;;
                    bmc_pass) bmc_pass="${val}" ;;
                    boot_mac) boot_mac="${val}" ;;
                esac
            done

            [[ -z "${bmc_ip}" ]] && die "Node '${name}': missing bmc_ip"
            [[ -z "${bmc_user}" ]] && die "Node '${name}': missing bmc_user"
            [[ -z "${bmc_pass}" ]] && die "Node '${name}': missing bmc_pass"
            [[ -z "${boot_mac}" ]] && die "Node '${name}': missing boot_mac"

            NODE_NAMES+=("${name}")
            NODE_BMC_IPS+=("${bmc_ip}")
            NODE_BMC_USERS+=("${bmc_user}")
            NODE_BMC_PASSES+=("${bmc_pass}")
            NODE_BOOT_MACS+=("${boot_mac}")
        fi
    done < "${INVENTORY}"

    [[ ${#NODE_NAMES[@]} -eq 0 ]] && die "No nodes found in inventory"
    info "Parsed ${#NODE_NAMES[@]} node(s) from inventory"
}

##############################################################################
# BMC verification via Redfish
##############################################################################

discover_redfish_system_id() {
    local bmc_ip="$1" bmc_user="$2" bmc_pass="$3"

    local systems_json
    systems_json=$(curl -sk --connect-timeout 5 --max-time 10 \
        -u "${bmc_user}:${bmc_pass}" \
        "https://${bmc_ip}/redfish/v1/Systems/" 2>/dev/null) || return 1

    echo "${systems_json}" | jq -r '.Members[0]."@odata.id"' 2>/dev/null
}

verify_bmc() {
    local name="$1" bmc_ip="$2" bmc_user="$3" bmc_pass="$4"
    local rc=0

    printf "  %-12s %-20s " "${name}" "${bmc_ip}"

    # Verify Redfish root is reachable and credentials work
    local http_code
    http_code=$(curl -sk --connect-timeout 5 --max-time 10 \
        -o /dev/null -w '%{http_code}' \
        -u "${bmc_user}:${bmc_pass}" \
        "https://${bmc_ip}/redfish/v1/" 2>/dev/null) || http_code="000"

    if [[ "${http_code}" == "200" ]]; then
        echo "OK (HTTP ${http_code})"
    elif [[ "${http_code}" == "401" ]]; then
        echo "FAIL — bad credentials (HTTP 401)"
        rc=1
    elif [[ "${http_code}" == "000" ]]; then
        echo "FAIL — unreachable"
        rc=1
    else
        echo "FAIL (HTTP ${http_code})"
        rc=1
    fi

    return ${rc}
}

verify_all_bmcs() {
    info "Verifying BMC credentials via Redfish"
    echo ""

    local failed=0
    for ((i = 0; i < ${#NODE_NAMES[@]}; i++)); do
        if ! verify_bmc "${NODE_NAMES[$i]}" "${NODE_BMC_IPS[$i]}" \
                "${NODE_BMC_USERS[$i]}" "${NODE_BMC_PASSES[$i]}"; then
            failed=$((failed + 1))
        fi
    done
    echo ""

    if [[ ${failed} -gt 0 ]]; then
        die "${failed} node(s) failed BMC verification"
    fi
    info "All BMC endpoints verified"
}

##############################################################################
# Artifact generation
##############################################################################

generate_ironic_nodes_json() {
    local output_file="$1"

    info "Generating ironic_nodes.json"

    local nodes_json='{"nodes":['
    local first=true

    for ((i = 0; i < ${#NODE_NAMES[@]}; i++)); do
        local name="${NODE_NAMES[$i]}"
        local bmc_ip="${NODE_BMC_IPS[$i]}"
        local bmc_user="${NODE_BMC_USERS[$i]}"
        local bmc_pass="${NODE_BMC_PASSES[$i]}"
        local boot_mac="${NODE_BOOT_MACS[$i]}"

        # Discover the Redfish system path from the BMC, fall back to standard
        local system_id
        system_id=$(discover_redfish_system_id "${bmc_ip}" "${bmc_user}" "${bmc_pass}" 2>/dev/null) || true
        system_id="${system_id:-/redfish/v1/Systems/1}"
        # Strip leading slash for URL construction
        system_id="${system_id#/}"

        ${first} || nodes_json+=","
        first=false

        nodes_json+=$(cat <<NODEJSON
{
    "name": "${name}",
    "driver": "redfish",
    "driver_info": {
      "address": "redfish://${bmc_ip}/${system_id}",
      "username": "${bmc_user}",
      "password": "${bmc_pass}",
      "redfish_verify_ca": "${BMC_VERIFY_CA}"
    },
    "ports": [
      {"address": "${boot_mac}"}
    ],
    "properties": {
      "cpu_arch": "${CPU_ARCH}"
    }
  }
NODEJSON
        )
    done

    nodes_json+=']}'

    echo "${nodes_json}" | jq . > "${output_file}"
    info "  → ${output_file}"
}

generate_baremetal_config() {
    local output_file="$1"
    local nodes_file_path="$2"

    info "Generating config_baremetal_fencing.sh"

    # Find the base config to derive from
    local base_config="${CONFIG_BASE}"
    if [[ -z "${base_config}" ]]; then
        local files_dir="${OC_DIR}/roles/dev-scripts/install-dev/files"
        if [[ -f "${files_dir}/config_fencing.sh" ]]; then
            base_config="${files_dir}/config_fencing.sh"
        elif [[ -f "${files_dir}/config_fencing_example.sh" ]]; then
            base_config="${files_dir}/config_fencing_example.sh"
        else
            die "No base config found. Provide one with --config-base."
        fi
    fi

    [[ -f "${base_config}" ]] || die "Base config not found: ${base_config}"
    info "  Base config: ${base_config}"

    {
        cat "${base_config}"
        echo ""
        echo "# Baremetal adoption overrides (generated by adopt-baremetal.sh)"
        echo "export NODES_PLATFORM=baremetal"
        echo "export NODES_FILE=\"${nodes_file_path}\""
    } > "${output_file}"

    info "  → ${output_file}"
}

##############################################################################
# Main
##############################################################################

main() {
    parse_args "$@"

    # Wizard if no inventory exists
    if [[ ! -f "${INVENTORY}" ]]; then
        run_wizard
    fi

    parse_inventory

    # BMC verification
    if ! ${SKIP_VERIFY}; then
        verify_all_bmcs
    fi

    if ${VERIFY_ONLY}; then
        info "Verification complete (--verify-only). No artifacts generated."
        exit 0
    fi

    # Create output directory
    local output_dir="${OC_DIR}/clusters/${CLUSTER_NAME}"
    mkdir -p "${output_dir}"

    # Generate artifacts
    local nodes_file="${output_dir}/ironic_nodes.json"
    generate_ironic_nodes_json "${nodes_file}"

    # NODES_FILE path on the hypervisor — resolves when dev-scripts sources the config
    local remote_nodes_path="\${PWD}/ironic_nodes.json"
    generate_baremetal_config "${output_dir}/config_baremetal_fencing.sh" "${remote_nodes_path}"

    echo ""
    info "Adoption complete. Generated artifacts:"
    echo "    ${nodes_file}"
    echo "    ${output_dir}/config_baremetal_fencing.sh"
    echo ""
    echo "  Next: deploy to hypervisor with the baremetal install workflow (OCPEDGE-2775)"
}

main "$@"
