#!/usr/bin/bash
#
# Unified status dashboard for the two-node-toolbox environment.
# Reports local configuration, EC2 instance state, cluster state file,
# hypervisor services (VMs, proxy, BMC simulator), and cluster API health.
# Every section degrades gracefully: a failing probe prints WARN/SKIP and
# the script moves on, so the dashboard is useful at any deployment stage.
#

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(cd "${SCRIPT_DIR}/../../" && pwd)"

# Suppress the generic instance.env warning from common.sh — the local config
# section already reports its absence with better guidance.
# shellcheck source=/dev/null
SKIP_INSTANCE_ENV_WARNING=1 source "${DEPLOY_DIR}/common.sh"

# Intentionally no errexit: probes are allowed to fail per section.
set -uo pipefail

INSTANCE_ENV="${DEPLOY_DIR}/aws-hypervisor/instance.env"
PROXY_ENV="${DEPLOY_DIR}/openshift-clusters/proxy.env"
INVENTORY_INI="${DEPLOY_DIR}/openshift-clusters/inventory.ini"

REGION="${REGION:-}"

STATUS_PASS="${COLOR_BLUE}[ OK ]${COLOR_CLEAR}"
STATUS_WARN="${COLOR_YELLOW}[WARN]${COLOR_CLEAR}"
STATUS_SKIP="${COLOR_YELLOW}[SKIP]${COLOR_CLEAR}"
STATUS_INFO="[INFO]"

section() {
    echo ""
    echo "=== $1 ==="
}

st_pass()  { echo -e "  ${STATUS_PASS} $1"; }
st_warn()  { echo -e "  ${STATUS_WARN} $1"; }
st_skip()  { echo -e "  ${STATUS_SKIP} $1"; }
st_info()  { echo -e "  ${STATUS_INFO} $1"; }

# Read an instance-data file, empty string when missing
read_node_file() {
    local file="$1"
    if [[ -f "${NODE_DIR}/${file}" ]]; then
        cat "${NODE_DIR}/${file}"
    else
        echo ""
    fi
}

NODE_DIR="$(get_node_dir)"
CONFIG_MISSING=false

#
# Section 1: Local configuration
#
section "Local configuration"

if [[ -f "${INSTANCE_ENV}" ]]; then
    st_pass "aws-hypervisor/instance.env present"
else
    st_warn "aws-hypervisor/instance.env missing - copy instance.env.template and set your values"
    CONFIG_MISSING=true
fi

if [[ -f "${PROXY_ENV}" ]]; then
    st_pass "openshift-clusters/proxy.env present"
else
    st_info "openshift-clusters/proxy.env not created yet - generated during cluster deployment"
fi

# inventory.ini is only needed to deploy a cluster and is generated by
# 'make inventory', so its absence is informational, never a warning.
if [[ -f "${INVENTORY_INI}" ]]; then
    st_pass "openshift-clusters/inventory.ini present"
else
    st_info "inventory.ini not created yet - run 'make inventory' before deploying a cluster"
fi

#
# Section 2: EC2 instance (includes everything 'make info' used to print)
#
section "EC2 instance"

INSTANCE_ID="$(read_node_file aws-instance-id)"
PUBLIC_ADDRESS="$(read_node_file public_address)"
SSH_USER="$(read_node_file ssh_user)"
STACK="$(read_node_file rhel_host_stack_name)"

HAVE_INSTANCE=false
INSTANCE_RUNNING=false

if [[ -z "${INSTANCE_ID}" ]]; then
    st_info "no instance found (no aws-instance-id in instance-data) - run 'make deploy' to create one"
else
    HAVE_INSTANCE=true
    [[ -n "${STACK}" ]] && st_info "Stack: ${STACK}"
    st_info "Instance ID: ${INSTANCE_ID}"
    [[ -n "${PUBLIC_ADDRESS}" ]] && st_info "Host: ${PUBLIC_ADDRESS}"
    [[ -n "${SSH_USER}" ]] && st_info "User: ${SSH_USER}"
    [[ -n "${PUBLIC_ADDRESS}" ]] && st_info "Cockpit URL: http://${PUBLIC_ADDRESS}:9090"

    if [[ -z "${REGION}" ]]; then
        st_warn "REGION not set (missing instance.env?) - skipping live AWS state query"
    elif ! command -v aws >/dev/null 2>&1; then
        st_warn "aws CLI not found - skipping live AWS state query"
    else
        AWS_RESULT="$(timeout 30 aws --region "${REGION}" ec2 describe-instances \
            --instance-ids "${INSTANCE_ID}" \
            --query 'Reservations[0].Instances[0].[State.Name,LaunchTime]' \
            --output text --no-cli-pager 2>&1)"
        AWS_STATUS=$?
        if [[ ${AWS_STATUS} -ne 0 ]]; then
            st_warn "could not query AWS (timeout, credentials, or instance gone): ${AWS_RESULT}"
        else
            INSTANCE_STATE="$(echo "${AWS_RESULT}" | awk '{print $1}')"
            LAUNCH_TIME="$(echo "${AWS_RESULT}" | awk '{print $2}')"
            if [[ "${INSTANCE_STATE}" == "running" ]]; then
                INSTANCE_RUNNING=true
                UPTIME_NOTE=""
                LAUNCH_EPOCH="$(date -u -d "${LAUNCH_TIME}" +%s 2>/dev/null || \
                    date -u -j -f "%Y-%m-%dT%H:%M:%S" "${LAUNCH_TIME%%.*}" +%s 2>/dev/null || echo "")"
                if [[ -n "${LAUNCH_EPOCH}" ]]; then
                    UPTIME_SECONDS=$(( $(date -u +%s) - LAUNCH_EPOCH ))
                    UPTIME_NOTE=" (up $(( UPTIME_SECONDS / 3600 ))h $(( (UPTIME_SECONDS % 3600) / 60 ))m)"
                fi
                st_pass "instance state: running${UPTIME_NOTE}"
                st_info "reminder: metal instances accrue cost while running - 'make stop' when not in use"
            else
                st_warn "instance state: ${INSTANCE_STATE}"
            fi
        fi
    fi
fi

#
# Section 3: Cluster state file
#
section "Cluster state file"

CLUSTER_STATE_FILE="$(get_shared_dir)/cluster-vm-state.json"
CLUSTER_TOPOLOGY=""

if [[ ! -f "${CLUSTER_STATE_FILE}" ]]; then
    st_info "no cluster-vm-state.json - no cluster has been deployed from this checkout"
else
    if command -v jq >/dev/null 2>&1; then
        CLUSTER_TOPOLOGY="$(jq -r '.topology // ""' "${CLUSTER_STATE_FILE}" 2>/dev/null || echo "")"
        CLUSTER_METHOD="$(jq -r '.installation_method // ""' "${CLUSTER_STATE_FILE}" 2>/dev/null || echo "")"
        CLUSTER_STATUS="$(jq -r '.status // ""' "${CLUSTER_STATE_FILE}" 2>/dev/null || echo "")"
    else
        CLUSTER_TOPOLOGY="$(grep -o '"topology":[[:space:]]*"[^"]*"' "${CLUSTER_STATE_FILE}" | cut -d'"' -f4 2>/dev/null || echo "")"
        CLUSTER_METHOD="$(grep -o '"installation_method":[[:space:]]*"[^"]*"' "${CLUSTER_STATE_FILE}" | cut -d'"' -f4 2>/dev/null || echo "")"
        CLUSTER_STATUS="$(grep -o '"status":[[:space:]]*"[^"]*"' "${CLUSTER_STATE_FILE}" | cut -d'"' -f4 2>/dev/null || echo "")"
    fi
    st_info "topology: ${CLUSTER_TOPOLOGY:-unknown}"
    st_info "installation method: ${CLUSTER_METHOD:-unknown}"
    st_info "last recorded status: ${CLUSTER_STATUS:-unknown}"
fi

#
# Section 4: Hypervisor (single SSH round trip)
#
section "Hypervisor"

if [[ "${HAVE_INSTANCE}" != "true" ]]; then
    st_skip "no instance - nothing to probe"
elif [[ "${INSTANCE_RUNNING}" != "true" ]]; then
    st_skip "instance is not confirmed running - skipping SSH probe"
elif [[ -z "${PUBLIC_ADDRESS}" || -z "${SSH_USER}" ]]; then
    st_skip "missing public_address or ssh_user in instance-data - cannot SSH"
else
    REMOTE_OUTPUT="$(timeout 30 ssh -o ConnectTimeout=10 -o BatchMode=yes \
        "${SSH_USER}@${PUBLIC_ADDRESS}" bash -s -- "${CLUSTER_TOPOLOGY}" 2>/dev/null << 'REMOTE_EOF'
        if ! sudo -n true 2>/dev/null; then
            echo "SUDO_FAILED"
        fi

        TOPOLOGY="$1"

        if [[ -d ~/openshift-metal3/dev-scripts ]]; then
            echo "DEVSCRIPTS present"
            CLUSTER_NAME="$(cd ~/openshift-metal3/dev-scripts && source common.sh >/dev/null 2>&1 && echo "${CLUSTER_NAME}")"
            if [[ -n "${CLUSTER_NAME}" ]]; then
                for vm in $(sudo virsh list --all --name 2>/dev/null | grep "^${CLUSTER_NAME}" || true); do
                    echo "VM ${vm} $(sudo virsh domstate "${vm}" 2>/dev/null || echo unknown)"
                done
            fi
        else
            echo "DEVSCRIPTS absent"
            # kcli or manual deployments: report all libvirt domains instead
            for vm in $(sudo virsh list --all --name 2>/dev/null | grep -v '^$' || true); do
                echo "VM ${vm} $(sudo virsh domstate "${vm}" 2>/dev/null || echo unknown)"
            done
        fi

        PROXY_STATUS="$(podman ps -a --filter name=external-squid --format '{{.Status}}' 2>/dev/null | head -1)"
        echo "PROXY ${PROXY_STATUS:-absent}"

        if [[ "${TOPOLOGY}" == "fencing" ]]; then
            if sudo podman container exists sushy-tools 2>/dev/null; then
                echo "BMC sushy-tools $(sudo podman inspect sushy-tools --format '{{.State.Status}}' 2>/dev/null || echo unknown)"
            elif systemctl --user list-unit-files ksushy.service >/dev/null 2>&1; then
                echo "BMC ksushy $(systemctl --user is-active ksushy.service 2>/dev/null || echo inactive)"
            else
                echo "BMC absent"
            fi
        fi
REMOTE_EOF
    )"
    SSH_STATUS=$?

    if [[ ${SSH_STATUS} -ne 0 ]]; then
        st_warn "hypervisor unreachable via SSH (${SSH_USER}@${PUBLIC_ADDRESS}) - skipping VM/proxy/BMC checks"
    else
        VM_COUNT=0
        while IFS= read -r line; do
            case "${line}" in
                "SUDO_FAILED")
                    st_warn "sudo access unavailable — VM and BMC status may be incomplete"
                    ;;
                "DEVSCRIPTS present")
                    st_pass "dev-scripts directory present (~/openshift-metal3/dev-scripts)"
                    ;;
                "DEVSCRIPTS absent")
                    st_info "no dev-scripts directory - listing all libvirt domains"
                    ;;
                VM\ *)
                    VM_NAME="$(echo "${line}" | awk '{print $2}')"
                    VM_STATE="$(echo "${line}" | cut -d' ' -f3-)"
                    VM_COUNT=$((VM_COUNT + 1))
                    if [[ "${VM_STATE}" == "running" ]]; then
                        st_pass "VM ${VM_NAME}: ${VM_STATE}"
                    else
                        st_warn "VM ${VM_NAME}: ${VM_STATE}"
                    fi
                    ;;
                PROXY\ *)
                    PROXY_STATE="${line#PROXY }"
                    if [[ "${PROXY_STATE}" =~ ^Up ]]; then
                        st_pass "proxy container external-squid: ${PROXY_STATE}"
                    elif [[ "${PROXY_STATE}" == "absent" ]]; then
                        st_info "proxy container external-squid not found (created during cluster deployment)"
                    else
                        st_warn "proxy container external-squid: ${PROXY_STATE} - try 'podman restart external-squid' on the host"
                    fi
                    ;;
                BMC\ absent)
                    st_warn "no BMC simulator found (sushy-tools container or ksushy service) - STONITH fencing may not work"
                    ;;
                BMC\ *)
                    BMC_KIND="$(echo "${line}" | awk '{print $2}')"
                    BMC_STATE="$(echo "${line}" | awk '{print $3}')"
                    if [[ "${BMC_STATE}" == "running" || "${BMC_STATE}" == "active" ]]; then
                        st_pass "BMC simulator (${BMC_KIND}): ${BMC_STATE}"
                    else
                        st_warn "BMC simulator (${BMC_KIND}): ${BMC_STATE} - STONITH fencing may not work"
                    fi
                    ;;
            esac
        done <<< "${REMOTE_OUTPUT}"
        if [[ ${VM_COUNT} -eq 0 ]]; then
            st_info "no cluster VMs found"
        fi
    fi
fi

#
# Section 5: Cluster API
#
section "Cluster API"

if [[ ! -f "${PROXY_ENV}" ]]; then
    st_skip "no proxy.env - cannot probe the cluster API"
elif ! command -v oc >/dev/null 2>&1; then
    st_warn "oc CLI not found - cannot probe the cluster API"
else
    NODES_OUTPUT="$(
        # shellcheck source=/dev/null
        source "${PROXY_ENV}" >/dev/null 2>&1
        timeout 15 oc get nodes --no-headers 2>/dev/null
    )"
    OC_STATUS=$?
    if [[ ${OC_STATUS} -ne 0 || -z "${NODES_OUTPUT}" ]]; then
        st_warn "cluster API unreachable through the proxy"
        st_info "if the cluster should be up, restart the proxy on the host: 'make ssh' then 'podman restart external-squid'"
    else
        READY_COUNT="$(echo "${NODES_OUTPUT}" | awk '$2 ~ /^Ready/' | wc -l)"
        NOT_READY_COUNT="$(echo "${NODES_OUTPUT}" | awk '$2 !~ /^Ready/' | wc -l)"
        if [[ ${NOT_READY_COUNT} -eq 0 ]]; then
            st_pass "cluster API reachable: ${READY_COUNT} node(s) Ready"
        else
            st_warn "cluster API reachable: ${READY_COUNT} node(s) Ready, ${NOT_READY_COUNT} node(s) not Ready"
            echo "${NODES_OUTPUT}" | awk '$2 !~ /^Ready/ {print "         " $1 ": " $2}'
        fi
    fi
fi

echo ""
if [[ "${CONFIG_MISSING}" == "true" ]]; then
    msg_warning "Configuration files are missing - see the 'Local configuration' section above."
fi
